### ISSUE TITLE
events not work

### ISSUE THREAD

**Issue by MrPoper** [Subtixx/vscode-mtalua#14] opened 2019-08-16 14:17 UTC
Issue Type: <b>Feature Request</b>

fix it and thx for developement team

Extension version: 2.3.6
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

**Comment by 0xCiBeR** [comment] 2020-09-26 18:53
What exactly doesnt work?

**Comment by Subtixx** [comment] 2020-09-26 19:34
There is no code completion for events, like 
`addEventHandler("onPlayerJoin")`

"onPlayerJoin" in this instance will not be code completed due to a "design flaw"

Same issue in https://github.com/Subtixx/vscode-mtalua/issues/13#issuecomment-484803338
> This is unfortunately with the current implementation not possible, since its not parsing the file just parses some characters after and before your cursor

Its a dupe of #11

**Closed as completed** 2021-07-27 17:39 UTC
Labels: duplicate
